// GENERATED by scripts/build-tokens.mjs. Do not edit.
export const primitives = {
  "purple/50": "#EEEDFD",
  "purple/100": "#DDDDFB",
  "purple/200": "#BBBAF7",
  "purple/300": "#9A98F4",
  "purple/400": "#7875F0",
  "purple/500": "#5653EC",
  "purple/600": "#3D10B5",
  "purple/700": "#1F0073",
  "purple/800": "#14004B",
  "purple/900": "#090023",
  "blue/50": "#EDF5FF",
  "blue/100": "#DBECFF",
  "blue/200": "#B7D8FF",
  "blue/300": "#93C5FF",
  "blue/400": "#6FB1FF",
  "blue/500": "#4B9EFF",
  "blue/600": "#3C7ECC",
  "blue/700": "#2D5F99",
  "blue/800": "#1E3F66",
  "blue/900": "#0F2033",
  "pink/50": "#FFF3F8",
  "pink/100": "#FFE7F1",
  "pink/200": "#FFCFE2",
  "pink/300": "#FFB6D4",
  "pink/400": "#FF9EC5",
  "pink/500": "#FF86B7",
  "pink/600": "#CC6B92",
  "pink/700": "#99506E",
  "pink/800": "#663649",
  "pink/900": "#331B25",
  "pink/950": "#1A0E13",
  "yellow/50": "#FFFBEF",
  "yellow/100": "#FFF8DE",
  "yellow/200": "#FEF1BE",
  "yellow/300": "#FEE99D",
  "yellow/400": "#FDE27D",
  "yellow/500": "#FDDB5C",
  "yellow/600": "#CAAF4A",
  "yellow/700": "#988337",
  "yellow/800": "#655825",
  "yellow/900": "#332C12",
  "gray/50": "#F9FAFB",
  "gray/100": "#F3F4F6",
  "gray/200": "#E5E7EB",
  "gray/300": "#D2D5DA",
  "gray/400": "#9CA3AF",
  "gray/500": "#6D7280",
  "gray/600": "#4B5563",
  "gray/700": "#374151",
  "gray/800": "#1F2937",
  "gray/900": "#111827",
  "base/black": "#000000",
  "base/white": "#FFFFFF",
  "night/950": "#0A0A18"
} as const;
export const alias = {
  "action/attention/bg": {
    "dark": "purple/500",
    "light": "purple/500"
  },
  "action/attention/bg-hover": {
    "dark": "purple/600",
    "light": "purple/600"
  },
  "action/attention/bg-pressed": {
    "dark": "purple/700",
    "light": "purple/700"
  },
  "action/attention/text": {
    "dark": "base/white",
    "light": "base/white"
  },
  "action/default/bg": {
    "dark": "purple/700",
    "light": "purple/700"
  },
  "action/default/bg-hover": {
    "dark": "purple/600",
    "light": "purple/600"
  },
  "action/default/bg-pressed": {
    "dark": "purple/800",
    "light": "purple/800"
  },
  "action/default/text": {
    "dark": "base/white",
    "light": "base/white"
  },
  "action/live/bg": {
    "dark": "blue/500",
    "light": "blue/500"
  },
  "action/live/bg-hover": {
    "dark": "blue/400",
    "light": "blue/400"
  },
  "action/live/bg-pressed": {
    "dark": "blue/300",
    "light": "blue/300"
  },
  "action/live/text": {
    "dark": "purple/700",
    "light": "purple/700"
  },
  "action/disabled/bg": {
    "dark": "gray/700",
    "light": "gray/100"
  },
  "action/disabled/text": {
    "dark": "gray/400",
    "light": "gray/400"
  },
  "surface/page": {
    "dark": "night/950",
    "light": "base/white"
  },
  "surface/section-alt": {
    "dark": "purple/700",
    "light": "purple/50"
  },
  "surface/card": {
    "dark": "purple/700",
    "light": "base/white"
  },
  "surface/card-raised": {
    "dark": "purple/600",
    "light": "purple/50"
  },
  "surface/live": {
    "dark": "blue/500",
    "light": "blue/500"
  },
  "text/primary": {
    "dark": "base/white",
    "light": "night/950"
  },
  "text/secondary": {
    "dark": "gray/200",
    "light": "gray/700"
  },
  "text/muted": {
    "dark": "gray/300",
    "light": "gray/600"
  },
  "text/inverse": {
    "dark": "night/950",
    "light": "base/white"
  },
  "text/link": {
    "dark": "purple/200",
    "light": "purple/600"
  },
  "border/subtle": {
    "dark": "purple/700",
    "light": "gray/100"
  },
  "border/strong": {
    "dark": "purple/400",
    "light": "gray/500"
  },
  "focus/ring": {
    "dark": "yellow/500",
    "light": "purple/600"
  },
  "highlight/yellow": {
    "dark": "yellow/500",
    "light": "yellow/500"
  },
  "highlight/pink": {
    "dark": "pink/500",
    "light": "pink/500"
  },
  "foundation/black": {
    "dark": "base/black",
    "light": "base/black"
  },
  "foundation/white": {
    "dark": "base/white",
    "light": "base/white"
  },
  "action/subtle/bg": {
    "dark": "purple/50",
    "light": "purple/50"
  },
  "action/subtle/bg-hover": {
    "dark": "purple/100",
    "light": "purple/100"
  },
  "action/subtle/bg-pressed": {
    "dark": "purple/200",
    "light": "purple/200"
  },
  "action/subtle/text": {
    "dark": "purple/700",
    "light": "purple/700"
  },
  "surface/light": {
    "dark": "purple/50",
    "light": "purple/50"
  },
  "surface/light-raised": {
    "dark": "purple/100",
    "light": "purple/100"
  },
  "text/on-light": {
    "dark": "purple/700",
    "light": "purple/700"
  },
  "text/on-light-muted": {
    "dark": "gray/600",
    "light": "gray/600"
  },
  "action/hover/bg": {
    "dark": "yellow/500",
    "light": "yellow/500"
  },
  "action/hover/text": {
    "dark": "purple/700",
    "light": "purple/700"
  },
  "text/link-hover": {
    "dark": "yellow/500",
    "light": "purple/700"
  },
  "accent/live": {
    "dark": "blue/500",
    "light": "blue/500"
  }
} as const;
export const spacing = {
  "space/0": 0,
  "space/4": 4,
  "space/8": 8,
  "space/12": 12,
  "space/16": 16,
  "space/20": 20,
  "space/24": 24,
  "space/32": 32,
  "space/40": 40,
  "space/48": 48,
  "space/64": 64,
  "space/80": 80,
  "space/96": 96,
  "space/128": 128,
  "radius/none": 0,
  "radius/sm": 8,
  "radius/md": 12,
  "radius/lg": 16,
  "radius/xl": 24,
  "radius/2xl": 32,
  "radius/full": 999,
  "size/icon-xs": 16,
  "size/icon-sm": 20,
  "size/icon-md": 24,
  "size/icon-lg": 40,
  "size/icon-tile-md": 48,
  "size/icon-tile": 64,
  "size/hit-min": 44,
  "size/button-min-sm": 200,
  "size/button-min-md": 240,
  "size/qr": 120,
  "size/qr-sm": 140,
  "size/qr-md": 210,
  "size/qr-lg": 280,
  "size/switch-w": 52,
  "size/switch-h": 32,
  "size/avatar-sm": 40,
  "size/avatar-md": 56,
  "size/avatar-lg": 80,
  "size/phone-w": 240,
  "size/phone-h": 522,
  "size/phone-h-crop": 340,
  "size/button-circle-sm": 36,
  "size/button-circle-md": 40,
  "size/glass-blur": 24,
  "size/step-indicator": 28,
  "size/step-separator": 2,
  "size/avatar-overlap-sm": 10,
  "size/avatar-overlap-md": 14,
  "size/card-media-desktop": 620,
  "size/card-media-mobile": 440,
  "size/hero-desktop": 1005,
  "size/hero-mobile": 780,
  "size/container-default": 1248,
  "size/container-narrow": 720
} as const;
export const gradients = {
  "scrim-top": {
    "direction": "to bottom",
    "from": "surface/page",
    "a0": 0.45,
    "a1": 0
  },
  "scrim-left": {
    "direction": "to right",
    "from": "surface/page",
    "a0": 0.6,
    "a1": 0
  },
  "scrim-bottom": {
    "direction": "to bottom",
    "from": "surface/page",
    "a0": 0,
    "a1": 0.6
  },
  "section-fade": {
    "direction": "to bottom",
    "from": "surface/light",
    "to": "surface/page",
    "steps": 10
  }
} as const;
export const shadows = {
  "nav-scrolled": {
    "x": 0,
    "y": 8,
    "blur": 15,
    "spread": 0,
    "color": "surface/page",
    "alpha": 0.1
  }
} as const;
export const typeStyles = [
  {
    "name": "Mobile/Display",
    "family": "Poppins",
    "style": "Bold",
    "size": 40,
    "lh": 44,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Mobile/H1",
    "family": "Poppins",
    "style": "Bold",
    "size": 34,
    "lh": 38,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Mobile/H2",
    "family": "Poppins",
    "style": "Bold",
    "size": 28,
    "lh": 34,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Mobile/H3",
    "family": "Poppins",
    "style": "Bold",
    "size": 20,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Body L",
    "family": "Poppins",
    "style": "Regular",
    "size": 17,
    "lh": 26,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Body",
    "family": "Poppins",
    "style": "Regular",
    "size": 16,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Small",
    "family": "Poppins",
    "style": "Regular",
    "size": 14,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Caption",
    "family": "Poppins",
    "style": "Medium",
    "size": 12,
    "lh": 16,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Label",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Eyebrow",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 12,
    "lh": 16,
    "ls": 6,
    "upper": true
  },
  {
    "name": "Mobile/Data",
    "family": "Poppins",
    "style": "Bold",
    "size": 32,
    "lh": 36,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Label L",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 18,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Headline/H1",
    "family": "Poppins",
    "style": "Bold",
    "size": 48,
    "lh": 56,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Mobile/Headline/H2",
    "family": "Poppins",
    "style": "Bold",
    "size": 40,
    "lh": 48,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Mobile/Headline/H3",
    "family": "Poppins",
    "style": "Bold",
    "size": 32,
    "lh": 40,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Mobile/Headline/H4",
    "family": "Poppins",
    "style": "Bold",
    "size": 24,
    "lh": 28,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Mobile/Headline/H5",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 20,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Headline/H6",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Title/Large",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 24,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Title/Medium",
    "family": "Poppins",
    "style": "Medium",
    "size": 20,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Title/Small",
    "family": "Poppins",
    "style": "Medium",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Body/Large",
    "family": "Poppins",
    "style": "Regular",
    "size": 20,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Body/Medium",
    "family": "Poppins",
    "style": "Regular",
    "size": 16,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Body/Small",
    "family": "Poppins",
    "style": "Regular",
    "size": 14,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Button/Large",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Button/Medium",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Mobile/Button/Small",
    "family": "Poppins",
    "style": "Medium",
    "size": 14,
    "lh": 20,
    "ls": 2,
    "upper": false
  },
  {
    "name": "Tablet/Headline/H1",
    "family": "Poppins",
    "style": "Bold",
    "size": 60,
    "lh": 72,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Tablet/Headline/H2",
    "family": "Poppins",
    "style": "Bold",
    "size": 48,
    "lh": 56,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Tablet/Headline/H3",
    "family": "Poppins",
    "style": "Bold",
    "size": 36,
    "lh": 44,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Tablet/Headline/H4",
    "family": "Poppins",
    "style": "Bold",
    "size": 32,
    "lh": 40,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Tablet/Headline/H5",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 24,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Headline/H6",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 20,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Title/Large",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 32,
    "lh": 40,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Title/Medium",
    "family": "Poppins",
    "style": "Medium",
    "size": 24,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Title/Small",
    "family": "Poppins",
    "style": "Medium",
    "size": 20,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Body/Large",
    "family": "Poppins",
    "style": "Regular",
    "size": 20,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Body/Medium",
    "family": "Poppins",
    "style": "Regular",
    "size": 16,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Body/Small",
    "family": "Poppins",
    "style": "Regular",
    "size": 14,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Button/Large",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 20,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Button/Medium",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Tablet/Button/Small",
    "family": "Poppins",
    "style": "Medium",
    "size": 14,
    "lh": 20,
    "ls": 2,
    "upper": false
  },
  {
    "name": "Desktop/Display",
    "family": "Poppins",
    "style": "Bold",
    "size": 72,
    "lh": 76,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Desktop/H1",
    "family": "Poppins",
    "style": "Bold",
    "size": 56,
    "lh": 62,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Desktop/H2",
    "family": "Poppins",
    "style": "Bold",
    "size": 48,
    "lh": 54,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Desktop/H3",
    "family": "Poppins",
    "style": "Bold",
    "size": 24,
    "lh": 32,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Body L",
    "family": "Poppins",
    "style": "Regular",
    "size": 19,
    "lh": 30,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Body",
    "family": "Poppins",
    "style": "Regular",
    "size": 16,
    "lh": 26,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Small",
    "family": "Poppins",
    "style": "Regular",
    "size": 14,
    "lh": 22,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Caption",
    "family": "Poppins",
    "style": "Medium",
    "size": 12,
    "lh": 18,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Label",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Eyebrow",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 14,
    "lh": 20,
    "ls": 6,
    "upper": true
  },
  {
    "name": "Desktop/Data",
    "family": "Poppins",
    "style": "Bold",
    "size": 40,
    "lh": 44,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Label L",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 18,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Headline/H1",
    "family": "Poppins",
    "style": "Bold",
    "size": 72,
    "lh": 88,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Desktop/Headline/H2",
    "family": "Poppins",
    "style": "Bold",
    "size": 56,
    "lh": 68,
    "ls": -2,
    "upper": false
  },
  {
    "name": "Desktop/Headline/H3",
    "family": "Poppins",
    "style": "Bold",
    "size": 44,
    "lh": 52,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Desktop/Headline/H4",
    "family": "Poppins",
    "style": "Bold",
    "size": 36,
    "lh": 44,
    "ls": -1,
    "upper": false
  },
  {
    "name": "Desktop/Headline/H5",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 28,
    "lh": 32,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Headline/H6",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 24,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Title/Large",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 36,
    "lh": 44,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Title/Medium",
    "family": "Poppins",
    "style": "Medium",
    "size": 28,
    "lh": 32,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Title/Small",
    "family": "Poppins",
    "style": "Medium",
    "size": 24,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Body/Large",
    "family": "Poppins",
    "style": "Regular",
    "size": 24,
    "lh": 32,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Body/Medium",
    "family": "Poppins",
    "style": "Regular",
    "size": 20,
    "lh": 28,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Body/Small",
    "family": "Poppins",
    "style": "Regular",
    "size": 16,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Button/Large",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 20,
    "lh": 24,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Button/Medium",
    "family": "Poppins",
    "style": "SemiBold",
    "size": 16,
    "lh": 20,
    "ls": 0,
    "upper": false
  },
  {
    "name": "Desktop/Button/Small",
    "family": "Poppins",
    "style": "Medium",
    "size": 14,
    "lh": 20,
    "ls": 2,
    "upper": false
  }
] as const;
