// Generates src/styles/tokens.css and src/styles/tokens.ts from tokens/figma-export.json.
// Never edit the generated files by hand: change the Figma file, re-export, run `npm run tokens`.
import { readFileSync, writeFileSync } from 'node:fs';

const src = JSON.parse(readFileSync(new URL('../tokens/figma-export.json', import.meta.url), 'utf8'));
const slug = (name) => name.replace(/\//g, '-');
const WEIGHT = { Regular: 400, Medium: 500, SemiBold: 600, Bold: 700 };
const lines = [];
const out = (s = '') => lines.push(s);

out('/* GENERATED by scripts/build-tokens.mjs from tokens/figma-export.json. Do not edit. */');
out(`/* Source: ${src.source} */`);
out('');
out('/* Primitives. Components never use these directly; they use the semantic tokens below. */');
out(':root {');
for (const [name, hex] of Object.entries(src.primitives)) out(`  --primitive-${slug(name)}: ${hex};`);
out('');
out('  /* Spacing, radius and size */');
for (const [name, value] of Object.entries(src.spacing)) out(`  --${slug(name)}: ${value}px;`);
out('');
out('  /* Typography: mobile values, desktop overrides below */');
out("  --font-family: 'Poppins', 'Helvetica Neue', Arial, sans-serif;");
out('}');
out('');

const semantic = (mode) => Object.entries(src.alias)
  .map(([name, v]) => `  --color-${slug(name)}: var(--primitive-${slug(v[mode])});`).join('\n');

out('/* Semantic colour tokens: Dark is the default theme. */');
out(`:root,\n[data-theme='dark'] {\n  color-scheme: dark;\n${semantic('dark')}\n}`);
out('');
out('/* Light values (Figma collection "Alias Light"). */');
out(`[data-theme='light'] {\n  color-scheme: light;\n${semantic('light')}\n}`);
out('');

// Gradients and shadows. Figma cannot bind a variable to them, so they are defined here from semantic colours.
out('/* Gradients and shadows: built from semantic colours so they follow the theme. */');
out(':root {');
const tint = (name, a) => `color-mix(in srgb, var(--color-${slug(name)}) ${+(a * 100).toFixed(1)}%, transparent)`;
for (const [name, g] of Object.entries(src.gradients ?? {})) {
  if (g.steps) {
    const stops = Array.from({ length: g.steps + 1 }, (_, i) => {
      const t = i / g.steps, k = t * t * (3 - 2 * t);
      return `color-mix(in srgb, var(--color-${slug(g.to)}) ${+(k * 100).toFixed(1)}%, var(--color-${slug(g.from)})) ${+(t * 100).toFixed(0)}%`;
    });
    out(`  --gradient-${name}: linear-gradient(${g.direction}, ${stops.join(', ')});`);
  } else {
    out(`  --gradient-${name}: linear-gradient(${g.direction}, ${tint(g.from, g.a0)}, ${tint(g.from, g.a1)});`);
  }
}
for (const [name, sh] of Object.entries(src.shadows ?? {}))
  out(`  --shadow-${name}: ${sh.x}px ${sh.y}px ${sh.blur}px ${sh.spread}px ${tint(sh.color, sh.alpha)};`);
out('}');
out('');

// Typography
const roles = {};
for (const s of src.styles) {
  const [bp, ...rest] = s.name.split('/');
  const role = slug(rest.join('/').toLowerCase().replace(/\s+/g, '-'));
  roles[role] ??= {};
  roles[role][bp.toLowerCase()] = s;
}
out('/* Type styles. Mobile is the base; Desktop applies from 768px (Figma breakpoint md). */');
out(':root {');
for (const [role, bps] of Object.entries(roles)) for (const [bp, s] of Object.entries(bps)) {
  out(`  --type-${role}-${bp}-size: ${s.size}px;`);
  out(`  --type-${role}-${bp}-line: ${s.lh}px;`);
  out(`  --type-${role}-${bp}-weight: ${WEIGHT[s.style]};`);
  out(`  --type-${role}-${bp}-tracking: ${+(s.ls / 100).toFixed(4)}em;`);
}
out('}');
out('');
const cls = (role, bp) => `font: var(--type-${role}-${bp}-weight) var(--type-${role}-${bp}-size)/var(--type-${role}-${bp}-line) var(--font-family);\n  letter-spacing: var(--type-${role}-${bp}-tracking);`;
for (const [role, bps] of Object.entries(roles)) {
  const extra = bps.mobile.upper ? '\n  text-transform: uppercase;' : '';
  const tab = role === 'data' ? '\n  font-variant-numeric: tabular-nums;' : '';
  out(`.type-${role} {\n  ${cls(role, 'mobile')}${extra}${tab}\n}`);
}
out('');
out('@media (min-width: 768px) {');
for (const role of Object.keys(roles)) out(`  .type-${role} {\n    ${cls(role, 'desktop')}\n  }`);
out('}');
writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), lines.join('\n') + '\n');

// Typed token names for docs and stories
const ts = `// GENERATED by scripts/build-tokens.mjs. Do not edit.
export const primitives = ${JSON.stringify(src.primitives, null, 2)} as const;
export const alias = ${JSON.stringify(src.alias, null, 2)} as const;
export const spacing = ${JSON.stringify(src.spacing, null, 2)} as const;
export const gradients = ${JSON.stringify(src.gradients ?? {}, null, 2)} as const;
export const shadows = ${JSON.stringify(src.shadows ?? {}, null, 2)} as const;
export const typeStyles = ${JSON.stringify(src.styles, null, 2)} as const;
`;
writeFileSync(new URL('../src/styles/tokens.ts', import.meta.url), ts);
console.log(`tokens.css: ${Object.keys(src.primitives).length} primitives, ${Object.keys(src.alias).length} semantic, ${Object.keys(src.spacing).length} spacing/size, ${Object.keys(roles).length} type roles`);
